-- LutorLMS baseline schema.
-- Generated from the JPA entities via Hibernate's PostgreSQL dialect
-- (see src/test/.../tools/SchemaExportTool to regenerate), so it matches
-- exactly what `spring.jpa.hibernate.ddl-auto=validate` expects.
--
-- Versioned V2 (not V1) on purpose: an early deploy baselined some databases at
-- version 1, which would skip a V1 migration. Naming this V2 guarantees it runs.
-- It is written idempotently (IF NOT EXISTS + guarded FKs) so it is safe whether
-- the target DB is brand-new or was previously created by Hibernate ddl-auto.

create table if not exists courses (
    id bigint generated by default as identity,
    description TEXT,
    image_url varchar(255),
    is_active boolean,
    price numeric(38,2) not null,
    title varchar(255) not null,
    video_url varchar(255),
    primary key (id)
);

create table if not exists users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    full_name varchar(255) not null,
    password varchar(255),
    role varchar(255) not null check (role in ('STUDENT','ADMIN','TEACHER')),
    primary key (id)
);

create table if not exists enrollment (
    id bigint generated by default as identity,
    enrollment_date timestamp(6) not null,
    is_active boolean not null,
    course_id bigint not null,
    user_id bigint not null,
    primary key (id)
);

create table if not exists modules (
    id bigint generated by default as identity,
    is_active boolean not null,
    sequence_order integer,
    title varchar(255) not null,
    video_url varchar(255),
    course_id bigint not null,
    primary key (id)
);

create table if not exists task (
    id bigint generated by default as identity,
    due_date timestamp(6),
    instructions TEXT,
    max_score integer,
    title varchar(255) not null,
    module_id bigint not null,
    primary key (id)
);

create table if not exists submission (
    id bigint generated by default as identity,
    file_url varchar(255) not null,
    score integer,
    submitted_at timestamp(6) not null,
    teacher_feedback TEXT,
    student_id bigint not null,
    task_id bigint not null,
    primary key (id)
);

create table if not exists payment_transactions (
    id bigint generated by default as identity,
    amount numeric(38,2) not null,
    completed_at timestamp(6),
    course_id bigint not null,
    created_at timestamp(6) not null,
    currency varchar(255) not null,
    paypal_capture_id varchar(255),
    paypal_order_id varchar(255) not null,
    status varchar(255) not null check (status in ('PENDING','COMPLETED','FAILED','CANCELED','REFUNDED')),
    user_id bigint not null,
    primary key (id)
);

create table if not exists subscriptions (
    id bigint generated by default as identity,
    amount numeric(38,2),
    canceled_at timestamp(6),
    cancellation_reason varchar(255),
    created_at timestamp(6),
    currency varchar(255),
    next_billing_date timestamp(6),
    paypal_plan_id varchar(255),
    paypal_subscription_id varchar(255),
    status varchar(255) not null check (status in ('ACTIVE','SUSPENDED','CANCELLED','APPROVAL_PENDING')),
    user_id bigint,
    version bigint,
    primary key (id)
);
CREATE TABLE verification_tokens (
                                     id          BIGSERIAL PRIMARY KEY,
                                     token       VARCHAR(64) NOT NULL UNIQUE,
                                     user_id     BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                                     expires_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_verification_tokens_token ON verification_tokens(token);
-- Foreign keys (added only if absent, so re-runs / adopted schemas don't error).
do $$ begin
    if not exists (select 1 from pg_constraint where conname = 'fk7ofybdo2o0ngc4de3uvx4dxqv') then
        alter table enrollment add constraint FK7ofybdo2o0ngc4de3uvx4dxqv foreign key (course_id) references courses;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk4x08no2mpupkr616h50w3aksx') then
        alter table enrollment add constraint FK4x08no2mpupkr616h50w3aksx foreign key (user_id) references users;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk8qnnp812q1jd38fx7mxrhpw9') then
        alter table modules add constraint FK8qnnp812q1jd38fx7mxrhpw9 foreign key (course_id) references courses;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fkjlg2bff2kbwi7yof7yc7fbokn') then
        alter table submission add constraint FKjlg2bff2kbwi7yof7yc7fbokn foreign key (student_id) references users;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fkh66q0hdbqk19lop36gyg3hvg0') then
        alter table submission add constraint FKh66q0hdbqk19lop36gyg3hvg0 foreign key (task_id) references task;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fkcx3dd0j2c7kpqqqnqs7428nfk') then
        alter table task add constraint FKcx3dd0j2c7kpqqqnqs7428nfk foreign key (module_id) references modules;
    end if;
end $$;
