-- Email verification support.
-- Adds the `enabled` flag to users (gated by email confirmation) and the
-- verification_tokens table that backs the one-time link sent on signup.
-- Written idempotently (IF NOT EXISTS + guarded FK) so it is safe on DBs
-- that may have been touched by an earlier ddl-auto run.

alter table users add column if not exists enabled boolean not null default false;

create table if not exists verification_tokens (
    id         bigint generated by default as identity,
    token      varchar(64) not null unique,
    user_id    bigint not null unique,
    expires_at timestamp(6) with time zone not null,
    primary key (id)
);

create index if not exists idx_verification_tokens_token on verification_tokens(token);

do $$ begin
    if not exists (select 1 from pg_constraint where conname = 'fk_verification_tokens_user') then
        alter table verification_tokens
            add constraint fk_verification_tokens_user
            foreign key (user_id) references users(id) on delete cascade;
    end if;
end $$;
