-- Adds category to courses and a course_ratings table.
-- - `category` is required by the entity (CourseCategory enum, stored as text).
--   We backfill existing rows to OTHER before adding the NOT NULL constraint.
-- - `course_ratings` is the source of the average star rating shown on cards
--   and the course detail page. One row per (user, course); upsert on rate.
-- Written idempotently so re-runs are safe.

do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_name = 'courses' and column_name = 'category'
    ) then
        alter table courses add column category varchar(64);
        update courses set category = 'OTHER' where category is null;
        alter table courses alter column category set not null;
        alter table courses
            add constraint courses_category_check
            check (category in ('PROGRAMMING','WEB_DEVELOPMENT','CLOUD','GAMING',
                                'FOREIGN_LANGUAGES','MATH','CHEMISTRY','BIOLOGY','OTHER'));
    end if;
end $$;

create table if not exists course_ratings (
    id bigint generated by default as identity,
    user_id bigint not null,
    course_id bigint not null,
    rating integer not null,
    created_at timestamp(6) not null,
    primary key (id)
);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'uk_course_ratings_user_course') then
        alter table course_ratings
            add constraint uk_course_ratings_user_course unique (user_id, course_id);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'course_ratings_rating_check') then
        alter table course_ratings
            add constraint course_ratings_rating_check check (rating between 1 and 5);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_course_ratings_user') then
        alter table course_ratings
            add constraint fk_course_ratings_user foreign key (user_id) references users(id);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk_course_ratings_course') then
        alter table course_ratings
            add constraint fk_course_ratings_course foreign key (course_id) references courses(id);
    end if;
end $$;

create index if not exists idx_course_ratings_course_id on course_ratings (course_id);
